# this is an update file and it should be used from the cerulean
# base image after a terraform deployment
name: fastai2
channels:
    - fastai
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - pip=22.0.4
    - cython
    - scikit-image
    - dask
    - tensorboard
    - pip:
          - eodag
          - pycocotools==2.0.4
          - icevision==0.12.0
          - fastai==2.5.5
          - fastcore>=1.3
