data_dir: ${data_dir}
num_workers: 8
bs: 32
num_samples: ???
chip_sz: 512
im_type: png
mount_path: "/root/data/"
img_dir: "/root/data/tiled_images_test_small_v2"
annotations_filepath: "/root/data/instances_slicks_test_v2_small.json"
label: sm_tag
label_list:
    - 'Infrastructure'
    - 'Natural Seep'
    - 'Coincident Vessel'
    - 'Recent Vessel'
    - 'Old Vessel'
    - 'Ambiguous'
    - 'Hard Negatives'

