_target_: icevision.Trainer
metric: IoUMetric
metric_type: IoUMetricType.mask
num_workers: 6
gpus: 1
precision: 16
min_epochs: 1
max_epochs: 30
log_every_n_steps: 2
reload_dataloaders_every_n_epochs: 1
