FROM lambgeo/lambda-gdal:3.2-python3.8
RUN pip install rasterio
RUN pip install rio-cogeo
RUN pip install click
RUN pip install joblib
RUN pip install tqdm
RUN pip install geopandas
RUN pip install rtree
RUN pip install pygeos
RUN pip install awscli

WORKDIR /mnt
