data_dir: ${data_dir}
num_workers: 8
bs: 4
chip_sz: 512
im_type: png
mount_path: "/root/data/"
img_dir: "/root/partitions/train-with-context-512/tiled_images"
annotations_filepath: "/root/partitions/train-with-context-512/instances_TiledCeruleanDatasetV2.json"
class_map: {"Infrastructure": 1,"Natural Seep": 2,"Coincident Vessel": 3,"Recent Vessel": 4,"Old Vessel": 5,"Ambiguous": 6,"Hard Negatives": 0,}

