model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 4

rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_score
    mode: max
    save_top_k: 1
    save_last: true
    verbose: true
    dirpath: 'logs/cp/'
    filename: '${name}-epoch={epoch:02d}-val_score={val_score:.2f}'
    auto_insert_metric_name: false

learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

layerwise_finetune:
    _target_: src.multihead.callbacks.LayerwiseFinetuning
    phase: 1

progressive_resizing:
    _target_: src.multihead.callbacks.ProgressiveResizing

